### ISSUE TITLE
Variant `$opts` get ignored

### ISSUE THREAD

**Issue by LucidityDesign** [miyagi-dev/miyagi#232]
As I understand the docs `getMergeMethod` should be called with every variant.
However the function only gets called with root data.

Therefore this variant `$opts` gets ignored:

```
$opts:
  array_name: overwrite
```

See:
https://github.com/miyagi-dev/miyagi/blob/c4e1112e6f396e69a9a394fb1ff13e384123f4e2/packages/core/lib/mocks/resolve.js#L14

Link to docs:
https://docs.miyagi.dev/how-to/writing-mock-data/#merging-arrays

**Comment by mgrsskls** [comment]
Hey @LucidityDesign,

can you give me some example data that is not working as expected?

**Comment by LucidityDesign** [comment]
This will always set `product-1` as first item in the `images` array:
```
title: Lorem Ipsum
images:
  - $ref: /elements/image#product-1
$opts:
  images: overwrite

$variants:
  - $name: Multiple images
    title: Pellentesque Dapibus
    $opts:
      images: overwrite
    images:
      - $ref: /elements/image#product-2
      - $ref: /elements/image#product-3
      - $ref: /elements/image#product-1
```
