### ISSUE TITLE
Referencing parts of other mock data

### ISSUE THREAD

**Issue by mgrsskls** [miyagi-dev/miyagi#305]
The idea would be to have something like this when referencing other mock data:

```
$ref: /template-components/frontpage/header/menu/dropdown#/items
```

or when referencing the mock data of a variant:

```
$ref: /template-components/frontpage/header/menu/dropdown#variant-name/items
```

**Comment by schalkneethling** [comment]
@mgrsskls Yes, please! I was also thinking one could borrow and idea from JSON Schema i.e.

```yml
# parent/moxks.yaml

form_action: /profile/edit

language_select_options:
  $anchor: LanguageSelectOptionsMock
  - type: option
    value: en
    label: English
    selected: true
  - type: option
    value: de
    label: German
  - type: option
    value: fr
    label: French
  - type: option
    value: es
    label: Spanish

profile_image:
  alt: "Profile image of Tiziana Lagomarsino"
  uri: /build/assets/img/dummy/avatar/6.webp
```

and then in another component

```yaml
# child.yaml in this instance

language_select_options:
  $ref: /components/apps/parent#LanguageSelectOptionsMock
```

**Comment by schalkneethling** [comment]
This option from you can also 100% work with the `$anchor` idea I shared:

```
$variants:
  - $name: foo
    items:
      $ref: #items

$defs:
  items: []
```
